# Alacritty Configuration File
#
# For more information, visit the Alacritty documentation:
#   https://alacritty.org/docs

# Terminal shell configuration
[terminal]
shell = "/bin/zsh"

# Font configuration
[font]
size = 16

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

# Window appearance and behavior
[window]
opacity = 0.9
padding.x = 2
padding.y = 2
decorations = "full" # Use full window decorations (title bar, buttons)
startup_mode = "Maximized" # Start Alacritty maximized

# Color scheme
[colors.primary]
background = "0x212121"
foreground = "0xc5c9de"

[colors.normal]
black = "0x181a29"
red = "0xF07178"
green = "0xcdea9f"
yellow = "0xffd47e"
blue = "0x93bbff"
magenta = "0xd3a7ee"
cyan = "0x98e4ff"
white = "0xbfd5de"

[colors.bright]
black = "0x282a40"
red = "0xeb7f84"
green = "0xe0ffad"
yellow = "0xffee7e"
blue = "0xa3c5ff"
magenta = "0xd6afed"
cyan = "0x98fffd"
white = "0xd1e5ed"

# Keyboard and mouse settings
[keyboard]
bindings = [
    { key = "V", mods = "Command", action = "Paste" },
    { key = "C", mods = "Command", action = "Copy" },
]

[mouse]
hide_when_typing = true